version: '3'
services:
  postgresql:
    image: postgres
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "6432:5432"
    volumes:
      - postgresql-local:/var/lib/postgresql/data/pgdata

volumes:
    postgresql-local:


