spring:
  application:
    name: spring-security
  jpa:
    # Provide database platform that is being used
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    # Show sql when spring data jpa performs query
    show-sql: true
    properties:
      hibernate:
        # Format queries
        format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASS}

server:
  error:
    include-stacktrace: never

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics
springdoc:
  swagger-ui:
    validatorUrl: null

jwt:
  signing-key: ${JWT_SIGNING_KEY}
  expiration-in-minutes: 60